package:
  name: pyfreeling
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
  run:
    - python
    - lxml

about:
  home: https://github.com/malev/pyfreeling/
  license: GNU
  summary: "Freeling with python"
